[mypy]
ignore_missing_imports = False
exclude = ^(tutorials/|tutorials/wip/|examples/wip/|build/|tests/test_models/generated/|tutorials/generated/)

[mypy-matplotlib.*,kvxopt.*,cvxopt.*,control.*,scipy.*,rclpy.*,std_msgs.*,tqdm.*,pandas.*,tensorflow.*,rospy.*,casadi.*,jaxopt.*,sympy.*,graphviz.*,pytest.*]
ignore_missing_imports = True
