version: '3.8'

services:
  cbfkit:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/home/cbfkit
      - ${SSH_KEYS_DIR:-~/.ssh}:/root/.ssh:ro
    stdin_open: true
    tty: true