version: '3.8'

services:
  cbfkit:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/home/cbfkit
      - ${SSH_KEYS_DIR:-}/:/root/.ssh:ro
    stdin_open: true
    tty: true
    environment:
      - SSH_KEYS_DIR