name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        pip install pytest pytest-cov python-dotenv
    - name: Lint with ruff
      if: matrix.python-version == '3.10'
      run: |
        pip install ruff
        # Stop the build if there are Python syntax errors or undefined names
        ruff check src --select=E9,F63,F7,F82 --target-version=py310
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ruff check src --exit-zero
    - name: Type check with mypy
      if: matrix.python-version == '3.10'
      run: |
        pip install mypy
        mypy src/cbfkit || true
    - name: Test with pytest
      run: |
        pytest -m "not slow" tests
    - name: Test slow tests
      if: matrix.python-version == '3.10'
      run: |
        pytest -m "slow" tests
